In [1]:
import pandas as pd

In [4]:
air_quality = pd.read_csv("data/air_quality_no2.csv", index_col=0, parse_dates=True)

In [5]:
air_quality.head()

                     station_antwerp  station_paris  station_london
datetime
2019-05-07 02:00:00              NaN            NaN            23.0
2019-05-07 03:00:00             50.5           25.0            19.0
2019-05-07 04:00:00             45.0           27.7            19.0
2019-05-07 05:00:00              NaN           50.4            16.0
2019-05-07 06:00:00              NaN           61.9             NaN

In [8]:
air_quality["ratio_paris_antwerp"] = (air_quality['station_paris'] / air_quality['station_london'])
air_quality.head()

,station_antwerp,station_paris,station_london,ratio_paris_antwerp
datetime,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000
2019-05-07 06:00:00,NaN,61.9,NaN,NaN

In [10]:
air_quality['london_mg_per_cubic'] = air_quality['station_london'] * 1.882
air_quality.head()

,station_antwerp,station_paris,station_london,ratio_paris_antwerp,londo_mg_per_cubic,london_mg_per_cubic
datetime,,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN,43.286,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789,35.758,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895,35.758,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000,30.112,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN,NaN

In [13]:
air_quality.head()

,station_antwerp,station_paris,station_london,ratio_paris_antwerp,london_mg_per_cubic
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [14]:
air_quality

,station_antwerp,station_paris,station_london,ratio_paris_antwerp,london_mg_per_cubic
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN
...,...,...,...,...,...
2019-06-20 22:00:00,NaN,21.4,NaN,NaN,NaN
2019-06-20 23:00:00,NaN,24.9,NaN,NaN,NaN
2019-06-21 00:00:00,NaN,26.5,NaN,NaN,NaN
2019-06-21 01:00:00,NaN,21.8,NaN,NaN,NaN
2019-06-21 02:00:00,NaN,20.0,NaN,NaN,NaN

In [15]:
air_quality_renamed = air_quality.rename(
    columns={
        "station_antwerp": "BETR801",
        "station_paris": "FR0414",
        "station_london": "London Westminister"
    }
)

In [16]:
air_quality_renamed.head()

,BETR801,FR0414,London Westminister,ratio_paris_antwerp,london_mg_per_cubic
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [17]:
air_quality_renamed = air_quality_renamed.rename(columns=str.lower)
air_quality_renamed

,betr801,fr0414,london westminister,ratio_paris_antwerp,london_mg_per_cubic
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,NaN,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,1.315789,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,1.457895,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,3.150000,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN
...,...,...,...,...,...
2019-06-20 22:00:00,NaN,21.4,NaN,NaN,NaN
2019-06-20 23:00:00,NaN,24.9,NaN,NaN,NaN
2019-06-21 00:00:00,NaN,26.5,NaN,NaN,NaN
2019-06-21 01:00:00,NaN,21.8,NaN,NaN,NaN
2019-06-21 02:00:00,NaN,20.0,NaN,NaN,NaN

In [21]:
air_quality_renamed['london_mg_per_cubic'].describe

<bound method NDFrame.describe of datetime
2019-05-07 02:00:00    43.286
2019-05-07 03:00:00    35.758
2019-05-07 04:00:00    35.758
2019-05-07 05:00:00    30.112
2019-05-07 06:00:00       NaN
                        ...
2019-06-20 22:00:00       NaN
2019-06-20 23:00:00       NaN
2019-06-21 00:00:00       NaN
2019-06-21 01:00:00       NaN
2019-06-21 02:00:00       NaN
Name: london_mg_per_cubic, Length: 1035, dtype: float64>