In [ ]:
import pandas as pd

In [ ]:
covid_df = pd.read_csv("italy-covid-daywise.csv")
covid_df.head()

In [ ]:
covid_df.info()

In [ ]:
covid_df.describe()

In [ ]:
covid_df.columns

In [ ]:
covid_df.shape

In [ ]:
import jovian

## Retrieving data from a data frame

In [14]:
# Pandas format is similar to this
covid_data_dict = {
    'date': ['2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03'],
    'new_cases': [1444, 1365, 996,  975, 1326],
    'new_death': [1, 4, 6, 8, 6],
    'new_tests': [53541, 42583, 54395, None, None]
}

In [15]:
# Pandas format is not similar to this
covid_data_list = [
    {'date': '2020-09-01', 'new_cases': 996, 'new_deaths': 6, 'new_tests': None},
    {'date': '2020-09-02', 'new_cases': 996, 'new_deaths': 6, 'new_tests': 3564},
    {'date': '2020-09-03', 'new_cases': 996, 'new_deaths': 6, 'new_tests': 77459},
]

In [16]:
covid_data_dict['new_cases']

[1444, 1365, 996, 975, 1326]

In [19]:
covid_df['new_cases'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: new_cases, dtype: float64

In [18]:
type(covid_df['new_cases'])

pandas.core.series.Series

Just like arrays, you can retrieve a specific value with a series using the indexing
notation []

In [20]:
covid_df['new_cases'][45]

np.float64(975.0)

In [22]:
covid_df['new_tests'][26]

np.float64(22999.0)

Pandas also provides the .at method to directly retrieve data at a specific row and column

In [23]:
covid_df.at[35, 'new_cases']

np.float64(210.0)

In [24]:
covid_df.at[20, 'new_tests']

np.float64(24113.0)

In [25]:
type(covid_df.at[15, 'new_deaths'])

numpy.float64

Instead of using the indexing notation [], Pandas also allow accessing columns as properties
of the data frame using the `.` notation. However, this method only works for columns whose 
names do not contain special characters

In [27]:
covid_df.new_cases.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: new_cases, dtype: float64

Further, you can also pass a list of columns within the indexing notation [] to access a subset of the
data frame with just the given columns

In [29]:
cases_df = covid_df[['date', 'new_cases']]
cases_df.head()

         date  new_cases
0  2019-12-31        0.0
1  2020-01-01        0.0
2  2020-01-02        0.0
3  2020-01-03        0.0
4  2020-01-04        0.0

Note, however that the new data frame `cases_df` is simply a 'view' of the original data frame `covid_df`.
Sometimes you might need a full copy of the data frame, in which case you use the `copy` method

In [30]:
covid_df_copy = covid_df.copy()

The data within `covid_df_copy` is completely separat from covid_df, and changing values inside one of them 
will not affect the other

To access a specific row of data, Pandas provides the `.loc` method

In [31]:
covid_df.loc[13]

date          2020-03-29
new_cases         5974.0
new_deaths         887.0
new_tests            NaN
Name: 13, dtype: object

Each retrieved row is also a Series object

In [32]:
type(covid_df.loc[13])

pandas.core.series.Series

In [33]:
covid_df.head(5)

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [34]:
covid_df.tail(10)

          date  new_cases  new_deaths  new_tests
37  2020-06-19      331.0        66.0    28570.0
38  2020-06-20     -148.0        47.0    29875.0
39  2020-06-21      264.0        49.0    24581.0
40  2020-06-22      224.0        24.0    16152.0
41  2020-06-23      221.0        23.0    23225.0
42  2020-08-30     1444.0         1.0    53541.0
43  2020-08-31     1365.0         4.0    42583.0
44  2020-09-01      996.0         6.0    54395.0
45  2020-09-02      975.0         8.0        NaN
46  2020-09-03     1326.0         6.0        NaN

In [35]:
covid_df.at[0, 'new_tests']

np.float64(nan)

In [36]:
type(covid_df.at[0, 'new_tests'])

numpy.float64

The distinction between 0 and NaN is subtle but important. In this dataset, it represents that daily test numbers
were not reported on specific dates

We can find the first index that doesn't contain an NaN values using `first_valid_index` method

In [37]:
covid_df.new_tests.first_valid_index()

15

Let's look at a few rows before and after the index to verify that the values indeed change from NaN to actual
numbers. We can do this by passing a range to loc

In [38]:
covid_df.loc[13 : 16]

          date  new_cases  new_deaths  new_tests
13  2020-03-29     5974.0       887.0        NaN
14  2020-03-30     5217.0       758.0        NaN
15  2020-04-21     2256.0       454.0    28095.0
16  2020-04-22     2729.0       534.0    44248.0

The .sample method can be used to retrieve a random sample of rows from the data frame

In [39]:
covid_df.sample(10)

          date  new_cases  new_deaths  new_tests
18  2020-04-24     2646.0       464.0    95273.0
23  2020-05-01     1872.0       285.0    43732.0
15  2020-04-21     2256.0       454.0    28095.0
12  2020-03-28     5959.0       971.0        NaN
29  2020-05-01     1444.0       369.0    13665.0
17  2020-04-23     3370.0       437.0    37083.0
43  2020-08-31     1365.0         4.0    42583.0
26  2020-05-01     1389.0       174.0    22999.0
4   2020-01-04        0.0         0.0        NaN
16  2020-04-22     2729.0       534.0    44248.0

Notice that even though we have taken a random sample, the original index of each row has been preserve. This is an
important and useful property of data frames - each row of data has an index associated with it.